name: Deployment (on runner)
on:
  push:
    branches:
      - master
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    # container:  #this time the job is directly on the rummer and not in a container
    #   image: node:16
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb # this is set according to the image requirments 
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017  # this time we don't have the local network of the container so we need the localhost ip and port for the service
      MONGODB_USERNAME: root # the same as the one in the service image
      MONGODB_PASSWORD: example # the same as the one in the service image
      PORT: 8080
    services:
      mongoDb: #label is up to us 
        image: mongo #we need to start with an image, as the service is in a container
        ports:
          - 27017:27017 #we forward the service port to the port on the runner machine
        env: # dependiong on the iammge additional env settings is provided
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example          
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
